apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: custom-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: iamanshik.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nextjs
            port:
              number: 3000
  - host: api.iamanshik.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: express-app-service
            port:
              number: 8080
  - host: "*.code.iamanshik.online"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-reverse-proxy
            port:
              number: 80
# minikube start --cpus=3 --memory=6500 && minikube stop && minikube start
#  minikube addons enable ingress
# minikube stop and start
# kubectl apply -f ./otherconfig/nginx-ingress.yaml