apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
  labels:
    app: code-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      labels:
        app: code-server
    spec:
      volumes:
        - name: code-server-volume
          hostPath:
            path: /home/anshik/k8svolume
            type: DirectoryOrCreate
      containers:
        - name: vite-react-container
          image: anshik12/ideserver:vite_react_app
          command:
            - code-server
          args:
            - --bind-addr
            - 0.0.0.0:8080
            - --auth
            - none
            - /home/vscode/code
            - --disable-telemetry
          ports:
            - containerPort: 8080
              name: code-server
            - containerPort: 3000
              name: react-port
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          volumeMounts:
            - name: code-server-volume
              mountPath: /home/vscode/code

---
apiVersion: v1
kind: Service
metadata:
  name: code-server-service
spec:
  type: NodePort
  selector:
    app: code-server
  ports:
    - name: code-server
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: react-port
      protocol: TCP
      port: 3000
      targetPort: 3000
